/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gestion.view;

import com.gestion.component.TableActionEvent;
import java.awt.event.ActionEvent;


/**
 *
 * @author routs
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent event, int row){
        btnEdit.addActionListener((ActionEvent ae) -> {
            event.onEdit(row);
        });
        btnDelete.addActionListener((ActionEvent ae) -> {
            event.onDelete(row);
        });

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new com.gestion.component.ActionButton();
        btnEdit = new com.gestion.component.ActionButton();

        setMaximumSize(new java.awt.Dimension(162, 32767));
        setMinimumSize(new java.awt.Dimension(162, 0));
        setPreferredSize(new java.awt.Dimension(162, 44));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion/icon/trash.png"))); // NOI18N

        btnEdit.setBackground(new java.awt.Color(204, 255, 204));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestion/icon/pencil.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gestion.component.ActionButton btnDelete;
    private com.gestion.component.ActionButton btnEdit;
    // End of variables declaration//GEN-END:variables
}
